### ISSUE TITLE
Oh ! One Bassoon and may be 2 others

### ISSUE THREAD

**Issue by Az-rhad** [digero/maestro#12]
Hello Digero
With the new release, you can have a normal bassoon in dashing pony at the instrument's seller and after two other bassoons with the "festival", one stacatto and one vibrato. So, can you update, when you have time Maestro ?
Thanks a lot from a Frenchy

**Comment by bodrovis** [comment]
Yep, +1 to this. And thanks for releasing such a great tool!

**Comment by cindagraham** [comment]
Here here! I third this request!

**Comment by NikolaiVChr** [comment]
I fourth it.

**Comment by digero** [comment]
The new bassoons are in version 2.5.0. Check it out at https://github.com/digero/maestro/releases

**Comment by bodrovis** [comment]
This is very cool, thank you!
