### ISSUE TITLE
Custom Soundfont for Maestro

### ISSUE THREAD

**Issue by NikolaiVChr** [digero/maestro#16]
Trying to get the ABC to sound like windows midi mapper, is not always good, as that midi mapper sounds like crap.

Since you already know how to work with Soundfonts as you do that with ABC I hope this is not a big thing to make.

I have some really good soundfonts and would really like to hear them in Maestro, when Original is selected.

Thanks again, for a great set of programs.

**Comment by digero** [comment]
This is out of the scope of Maestro.

You could replace LotroInstruments.sf2 in the installation folder with your own SoundFont, and it'll use those instruments as the "ABC Preview", as long as the instrument preset numbers match those in the original LotroInsturments.sf2. (See the preset program numbers at the bottom of https://github.com/digero/maestro/blob/master/audio/LotroInstruments/LotroInstruments.txt)

You could also fork Maestro and modify the code to use a custom SoundFont for the regular MIDI playback. Check out SynthesizerFactory and LotroSequencerWrapper to get started.
