### ISSUE TITLE
Java Issue

### ISSUE THREAD

**Issue by Morganfey** [digero/maestro#25]
Today when I started up Maestro, I received a message that it requires Java 7.0 32 bit or higher.  I have Java 8 64 bit.  I have uninstalled and reinstalled both Maestro and Java.  Any help, please?

**Comment by digero** [comment]
You need to install the 32-bit version of Java. Maestro doesn't work with the 64-bit version. (You can have both 32-bit and 64-bit installed at the same time if you need.)

Sorry the error message isn't clearer about that!

**Comment by Morganfey** [comment]
Ohhh , thank you.  I found a work around by just using the .jar files for Maestro and ABCplayer.   I put them on my desktop instead of the .exe files and all seems to work ok.

 

Thanks again.

 

Mary/Frie
