### ISSUE TITLE
ABC player wont play this file, but LOTRO plays it

### ISSUE THREAD

**Issue by NikolaiVChr** [digero/maestro#29]
It says: unable to read tempo

Here is the file:
[eco.zip](https://github.com/digero/maestro/files/5012033/eco.zip)

**Comment by digero** [comment]
The tempo specification in that file is not valid according to the ABC format spec (http://abcnotation.com/wiki/abc:standard:v2.1#qtempo).
You have:
`Q:118 =1/4`
It should be:
`Q: 1/4=118`

I guess LOTRO ignores the invalid syntax, but I don't intend to try to match every quirk of LOTRO's ABC parsing in ABC player.
