### ISSUE TITLE
Failed to initialize MIDI sequencer

### ISSUE THREAD

**Issue by ZachBora** [digero/maestro#4]
Hello,

I'm getting an error when starting up maestro. Maestro v2.3.0

> Failed to initialize MIDI sequencer.
> The program will now exit.
> 
> Error details:
> A device ID has been used that is out of range for your system.

**Comment by bobsmynaim** [comment]
Yeah, me too. It just happened after my latest win 10 update. I tried a system restore (from when it was still working) which failed, so I uninstalled/reinstalled Maestro and got the same message. Updated Java with no luck. Guess I'll have to try restore to an earlier date.

**Comment by digero** [comment]
That is indicating that Java can't get your system MIDI sequencer. Make sure you have all system updates installed via Windows Update, and that you have the correct drivers installed for your sound card.

You can also try searching online for "A device ID has been used that is out of range for your system." or "MidiUnavailableException" to see if there are other things you can try.
