### ISSUE TITLE
New instruments: Fiddles

### ISSUE THREAD

**Issue by NikolaiVChr** [digero/maestro#7]
The first fiddle has been introduced to LOTRO.

Would be nice to have in Maestro.

This is the list of them, only the first one is in-game on live server now.

Student's Fiddle / Expedition Fiddle
Sprightly Fiddle
Traveller's Trusty Fiddle
Lonely Mountain Fiddle
Basic Fiddle (Devs talked about maybe adding this too, same as student but include the lowest 7 notes instead of noises)

**Comment by NikolaiVChr** [comment]
From https://www.lotro.com/en/game/articles/meet-fiddle:

> The lowest note it can play is G3 (or G2 within our ABC system). That leaves seven notes below it that don't produce any sound. As much as I'd love for the instrument to have a full three octaves, doing so would have required us to either synthetically pitch down notes to fill in the gaps (notes a real fiddle can't play), or cut off the bottom notes (G3-B3) and add on notes to the upper octave (which is less than ideal because the low notes have nice resonance and the higher you get on the instrument the thinner the sound becomes). The unfortunate side effect of this technical limitation is that the fiddle doesn't always plug in nicely to all existing ABC files that you've created, and will require some effort on your part to tailor your ABC files to best utilize the fiddle.

**Comment by digero** [comment]
New fiddles are in 2.4.1!
