### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by Az-rhad** [digero/maestro#8]
Hello,
No possibilities to save the new fiddles .... No name changement, nor sound !
I had to downgrade to Nikolai Releases :( 
Can you take a look ?

**Comment by Needabrew** [comment]
Yes I have the same problem.  Saving as .msx has the changes to the new insts in it, but exporting to ABC keeps the old value.  I edited an existing abc file changing an instrument to new fiddle.

**Comment by digero** [comment]
I'm having trouble reproducing this or understanding exactly what the bug is. Could you list step-by-step instructions for reproducing it? (be as specific as possible)

It would help if you attach .mid, .msx, and .abc files that have the problem, too.

For example:
> _1. Open the attached midi file in Maestro_
> _2. Add a Traveller's Trusty Fiddle part and add track 2 to it_
> _3. Export to ABC_
> _4. Open the ABC file in ABC Player, and it uses Basic Lute when it should use Traveller's Trusty Fiddle._

Thanks!

**Comment by Needabrew** [comment]
More info on this.  If you change the instrument in the pull-down list, you HAVE to manually type in the exact name as the pull down in the Part name box, or after exporting, it will play the first instrument that matches the Part name rather than the instrument in the pull-down list.  Sent you files. I do believe this to be in error, as it should be picking up the instrument from the pull-down, not the part name.

And thank you!

**Comment by Az-rhad** [comment]
Excuse my english, i'm French ...
Like Needabrew say, you have to change the part name. For example : 
Opening a ABC File 
![image](https://user-images.githubusercontent.com/13099012/39351314-66a5e4a2-4a01-11e8-8e8c-bba694b04347.png)
Changing the fiddle by an other fiddle : 
![image](https://user-images.githubusercontent.com/13099012/39351453-d95cf468-4a01-11e8-95fe-3a27c247c104.png)
Nothing happen. And if save, nothing happen but the new fiddle disappear : 
![image](https://user-images.githubusercontent.com/13099012/39351757-cd7de9b2-4a02-11e8-80a9-66170c925aaa.png)
But if i change part name and put the exact instrument : 
![image](https://user-images.githubusercontent.com/13099012/39351800-f1f962da-4a02-11e8-8d1c-5b1f4b754cb6.png)
and i save
![image](https://user-images.githubusercontent.com/13099012/39352065-d54573da-4a03-11e8-8847-3e3fc6fe709e.png)
It is good !
I hope that this can help you.

**Comment by Az-rhad** [comment]
In fact, I'm think the problem is only when you have a "Student Fiddle No FX" as an instrument ! 
No problem to change other instruments to fiddle ! Only when No Fx is before selectionned.

**Comment by Needabrew** [comment]
Any update on this bug? Have you been able to reproduce it?

Thanks!

**Comment by digero** [comment]
I think this should be fixed in v2.5.0. Let me know if it's still not working as you expect. You can download it here: https://github.com/digero/maestro/releases

**Comment by Hannariel** [comment]
Oh, my gosh! Thank you so much! 

Our band has been patiently waiting for this. We so appreciate the work you do for the music community in lotro, even though you aren't actively playing any more. 

Hannariel, Fluffy Unicorn bandleader

**Comment by PepeDitty** [comment]
Thanks Digero, you are a true artist, been waiting for the update, again thank you so much, Superb work!
